### ISSUE TITLE
Does not handle /* */ comments in CSS

### ISSUE THREAD

**Issue by gtasker10** [mattkenefick/vscode-css-alphabetize#7]
If I highlight this block in my CSS:

   .draggable {
      background-color: white;
      cursor: move; /* fallback: no `url()` support or images disabled */
      cursor: url(images/grab.cur);/* fallback: Chrome 1-21, Firefox 1.5-26, Safari 4+, IE, Edge 12-14, Android 2.1-4.4.4 */
      cursor: grab;/* W3C standards syntax, all modern browser */
   }

The formatting breaks the CSS, creating this mess:

   .draggable {
      background-color: white;
      cursor: grab;
      cursor: move;
      cursor: url(images/grab.cur);
      fallback: Chrome 1-21, Firefox 1.5-26, Safari 4+, IE, Edge 12-14, Android 2.1-4.4.4 */
      fallback: no `url()` support or images disabled */
      
       /* 
      /* 
      /* W3C standards syntax, all modern browser */
   }

**Comment by mattkenefick** [comment]
Should be resolved in 0.3.0.

Previous: 
<img width="680" alt="image" src="https://github.com/mattkenefick/vscode-css-alphabetize/assets/149809/2b7a7dc2-04b5-4b5b-8ff0-54dbe2731073">

0.3.0:
<img width="663" alt="image" src="https://github.com/mattkenefick/vscode-css-alphabetize/assets/149809/25fdd65e-32cb-4994-a575-48dbb5f5621d">

**Comment by smoochy** [comment]
I just stumbled accross this, and there is still a bug present.

Your fix only works, if I manually type `/* */` around the code.

If I mark my code and comment it out via `Edit -> Toggle Line Comment` and then alphabetize, the comments get separated again, and the code is not commented out.


Example:

```css
#navbar #header {
  font-size: 32px;
  padding: 20px 0px 20px 10px;
}
```

I want to comment out the font-size. When I manually type `/* */` around that code and then alphabetize, it results in:

```css
#navbar #header {
  padding: 20px 0px 20px 10px;
  /* font-size: 32px;*/
}
```

When I mark `font-size: 32px;` and Toggle Line Comment it results in that:
```css
#navbar #header {
  font-size: 32px;
  padding: 20px 0px 20px 10px;

  /*  */
}
```
