### ISSUE TITLE
Still does not handle /* */ comments correctly in CSS

### ISSUE THREAD

**Issue by smoochy** [mattkenefick/vscode-css-alphabetize#9]
I open up a new issue, to make it more visible.

I stumbled accross the issue with mal-formatting comments and your fix,but there is still a bug present.

Your fix only works, if I manually type `/* */` around the code.

If I mark my code and comment it out via `Edit -> Toggle Line Comment` and then alphabetize, the comments get separated again, and the code is not commented out.

Example:

```css
#navbar #header {
  font-size: 32px;
  padding: 20px 0px 20px 10px;
}
```

I want to comment out the font-size. When I manually type `/* */` around that code and then alphabetize, it results in:

```css
#navbar #header {
  padding: 20px 0px 20px 10px;
  /* font-size: 32px;*/
}
```

When I mark `font-size: 32px;` and Toggle Line Comment it results in that:
```css
#navbar #header {
  font-size: 32px;
  padding: 20px 0px 20px 10px;

  /*  */
}
```

_Originally posted by @smoochy in https://github.com/mattkenefick/vscode-css-alphabetize/issues/7#issuecomment-1902141725_
